### ISSUE TITLE
can't sync after 4721900

### ISSUE THREAD

**Issue by olizax** [aionnetwork/aion#1089]
## Description
cant't synced after height 4721900, there are error messages in the log.

> ERROR CONS [sync-ib]: Attempting to add INVALID block.

PS:  the Fork.properties and genesis.json file have been modified exactly as the Migration guide.

## System Information

I'm running:

- **Which Aion version?**: 1.0.674e4b5
- **Which operating system?**: Linux
- **Which distributor and version?**: Ubuntu 18.04
- **How installed?**: via binaries 
- **Are you fully synchronized?**: no 
- **Did you try to restart the node?**: yes

**Comment by AlexandraRoatis** [comment]
The issue is due to an incorrect setting of the 1.0 fork. Please ensure that the fork file that was updated is `mainnet/config/fork.properties`. It must contain the line `fork1.0=4721900`.

As you start the kernel it should print out `<Protocol name: fork1.0 block#: 4721900` if the fork was set correctly. The `USED PATHS` messages allow you to locate the exact file that is read from disk, in case the fork message is still incorrect or missing.
